image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - "test"
  - "build"
  - "deploy"

TestApp:
    stage: "test"
    script: 
            - yarn
            - yarn test

buildReact:
    stage: "build"
    script:
        - yarn
        - yarn build

deploy:
  stage: "deploy"
  type: deploy
  image: ruby:latest
  script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
        - master
    


